// src/App.jsx
import React, { useState } from 'react'

function App() {
  const [count, setCount] = useState(0)

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center">
      <div className="bg-white rounded-lg shadow-xl p-8 max-w-md w-full">
        <h1 className="text-4xl font-bold text-center mb-6 text-indigo-600">
          ChatBot Frontend
        </h1>
        <p className="text-gray-600 text-center mb-8">
          React + Tailwind CSS Setup
        </p>
        
        <div className="bg-indigo-50 rounded-lg p-6 mb-6">
          <p className="text-center text-2xl font-semibold text-indigo-800 mb-4">
            Count: {count}
          </p>
          <button
            onClick={() => setCount(count + 1)}
            className="w-full bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-3 px-6 rounded-lg transition duration-200 transform hover:scale-105 active:scale-95"
          >
            Increment Counter
          </button>
        </div>

        <div className="space-y-2 text-sm text-gray-500">
          <p className="flex items-center justify-center">
            <span className="inline-block w-2 h-2 bg-green-500 rounded-full mr-2"></span>
            React is running
          </p>
          <p className="flex items-center justify-center">
            <span className="inline-block w-2 h-2 bg-green-500 rounded-full mr-2"></span>
            Tailwind CSS is configured
          </p>
        </div>
      </div>
    </div>
  )
}

export default App

// src/App.vue
<script setup></script>

<template>
  <div
    class="min-h-screen bg-gradient-to-br from-blue-500 to-purple-600 flex items-center justify-center p-8"
  >
    <div class="bg-white rounded-2xl shadow-2xl p-8 max-w-2xl">
      <h1 class="text-4xl font-bold text-gray-800 mb-4">🎨 Tailwind CSS is Working!</h1>
      <p class="text-gray-600 mb-6">
        If you can see styled content with colors and shadows, Tailwind is properly configured.
      </p>

      <div class="grid grid-cols-3 gap-4 mb-6">
        <div class="bg-red-500 text-white p-4 rounded-lg text-center font-semibold">Red</div>
        <div class="bg-green-500 text-white p-4 rounded-lg text-center font-semibold">Green</div>
        <div class="bg-blue-500 text-white p-4 rounded-lg text-center font-semibold">Blue</div>
      </div>

      <button
        class="bg-purple-600 hover:bg-purple-700 text-white font-bold py-3 px-6 rounded-lg transition duration-300 transform hover:scale-105 shadow-lg"
      >
        Click Me!
      </button>
    </div>
  </div>
</template>

<style scoped></style>
